### ISSUE TITLE
policy variable doesn't accept input for a custom bucket policy

### ISSUE THREAD

**Issue by lr-carmichael** [cloudposse/terraform-aws-cloudtrail-s3-bucket#19]
We want to add arns to the bucket policy after creation, and could find no way to add a custom policy.   The first time a run occurs, the bucket policy gets populated, but only with the existing accounts.

If you try to add a custom policy, it gets ignored.

As a workaround, I configured a normal input and then point that to a valid json with all of our account arns.

```terraform
  #policy                             = join("", data.aws_iam_policy_document.default.*.json)
  policy                             = var.policy
```

What would be ideal though is if it worked both ways.  So first create the default policy, and then if you define a policy that added whatever you needed:

`policy    = file("policies/cloudtrail-bucket.json")`

Or even better a list of arns to add to the policy dynamically.

**Comment by abeluck** [comment]
Just ran into this myself too :(

**Comment by stephgosling** [comment]
ditto

**Comment by amontalban** [comment]
Same here :(

**Comment by jamengual** [comment]
PRs are welcome
