### ISSUE TITLE
Make forceDestroy a variable

### ISSUE THREAD

**Issue by analytically** [cloudposse/terraform-aws-cloudtrail-s3-bucket#2]

**Comment by aknysh** [comment]
@analytically 
thanks for testing and comments. Nice catch!
we'll update the repo with your suggestions.

**Comment by aknysh** [comment]
@analytically 
this has been implemented and merged to master
https://github.com/cloudposse/terraform-aws-cloudtrail-s3-bucket/releases/tag/0.1.1
thanks for your contribution!
