### ISSUE TITLE
Upgrade s3-log-storage dependency to 1.0.0

### ISSUE THREAD

**Issue by ghost** [cloudposse/terraform-aws-cloudtrail-s3-bucket#68]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Using this module introduces a deprecation message regarding the use of "versioning" attribute of the s3 bucket created by this module.

## Expected Behavior
No deprecation messages appear when using the latest release of this module

## Steps to Reproduce
```
module "cloudtrail_s3_bucket" {
  source  = "cloudposse/cloudtrail-s3-bucket/aws"
  version = "0.23.1"
}
```
## Screenshots
```
╷
│ Warning: Argument is deprecated
│ 
│   with module.cloudtrail_s3_bucket.module.s3_bucket.aws_s3_bucket.default[0],
│   on .terraform/modules/cloudtrail_s3_bucket.s3_bucket/main.tf line 1, in resource "aws_s3_bucket" "default":
│    1: resource "aws_s3_bucket" "default" {
│ 
│ Use the aws_s3_bucket_versioning resource instead
│ 
│ (and 4 more similar warnings elsewhere)
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
MacOS 11.7.1
Terraform 1.2.7

## Additional Context
This can be fixed by incrementing the version of the depedency "cloudposse/s3-log-bucket" to 1.0.0 (to get AWS v4 provider support). It is possible that an interim version might also work but the release notes for your own module say not to use non 1.0 releases of s3-log-bucket.

**Comment by Nuru** [comment]
Closed by #67
