### ISSUE TITLE
MalformedPolicy: Policy has invalid resource

### ISSUE THREAD

**Issue by kmishra9** [cloudposse/terraform-aws-cloudtrail-s3-bucket#7]
Hey there, 

While running the module:
```hcl
module "cloudtrail" {
  source                        = "git::https://github.com/cloudposse/terraform-aws-cloudtrail.git?ref=master"

  name                          = "${var.project_name}-cloudtrail"
  namespace                     = "${var.organization_name}"
  s3_bucket_name                = "${module.cloudtrail_s3_bucket.bucket_id}"
  stage                         = "${var.stage}"

  enable_log_file_validation    = "true"
  enable_logging                = "true"
  include_global_service_events = "true"
  is_multi_region_trail         = "true"
}

module "cloudtrail_s3_bucket" {
  source    = "git::https://github.com/cloudposse/terraform-aws-cloudtrail-s3-bucket.git?ref=master"

  name      = "${var.project_name}-logs"
  namespace = "${var.organization_name}"
  stage     = "${var.stage}"

  force_destroy = "False"
  region    = "${var.region}"
}
```
I ran into the following error:
```bash
Error: Error applying plan:

1 error(s) occurred:

* module.cloudtrail.module.cloudtrail_s3_bucket.module.s3_bucket.aws_s3_bucket.default: 1 error(s) occurred:


* aws_s3_bucket.default: Error putting S3 policy: MalformedPolicy: Policy has invalid resource
        status code: 400, request id: CB2E512B37853ED7, host id: LNk/8ZqsRo59sUtia3gQ2JEEFcTu37jeFkKodi3Lq8J
rJ84EsdSqj4eMlxquxI65b+uoZXsyoGE=
```
I took a look at the source code of the module and my own call and nothing seems egregious. As far as I know, I have no control (besides what `${module.label.id}` evaluates to) over the AWS IAM policy being applied to the S3 bucket so I'm not sure why I'm getting this.

**Comment by kmishra9** [comment]
Ok, it actually appears to work after a `terraform destroy` and rerun of `terraform apply`. However, what I think caused the issue and may be something that could be better guarded against was the following scenario:

Set`project_name = tf_test` and originally the `name` argument in both modules was `"${var.project_name}_cloudtrail"` and `"${var.project_name}_logs"`. This caused an error and told me that only alphanumeric and hyphen characters were allowed. So then I changed `project_name = tf-test` and changed the underscores to hyphens in the variable interpolation and re-terraform apply'd. 

My guess is that changing those variables did not force a recompute and recreation of resources correctly and when the policy went to look for the s3 bucket using `${module.label.id}`, it was unable to find the updated bucket

**Comment by aknysh** [comment]
we converted the module to TF 0.12.
see https://github.com/cloudposse/terraform-aws-cloudtrail-s3-bucket/releases/tag/0.4.0
will close this for now, please reopen if any issues
