### ISSUE TITLE
InvalidBucketAclWithObjectOwnership

### ISSUE THREAD

**Issue by yushkevicham** [cloudposse/terraform-aws-cloudtrail-s3-bucket#71]
## Describe the Bug
Error when terraform apply 
InvalidBucketAclWithObjectOwnership: Bucket cannot have ACLs set with ObjectOwnership's BucketownerEnforced setting
## Expected Behavior
Expect S3 bucket to be created successfully on first pass without ACL error
this is related to this https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

## Steps to Reproduce
1. Create test.tf file
2. terraform init (terraform version 1.4.5)
3. terraform apply
3. See error

## Screenshots
![image](https://user-images.githubusercontent.com/97115964/234975854-d8ce2fdd-6d77-46b5-ad40-19201aad54a7.png)

**Comment by Nuru** [comment]
Closed by #67
