### ISSUE TITLE
Why does this module lack features such as glacier transition which are included with terraform-aws-s3-log-storage?

### ISSUE THREAD

**Issue by slmingol** [cloudposse/terraform-aws-cloudtrail-s3-bucket#8]
Curious why features such as expiration_days & glacier_transition_days existing in this module https://github.com/cloudposse/terraform-aws-s3-log-storage but are absent in this module?

**Comment by aknysh** [comment]
@slmingol  good point
please open a PR for that, we'll review promptly

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-cloudtrail-s3-bucket/pull/10
